apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: isdialogmelding
  namespace: teamsykefravr
  labels:
    team: teamsykefravr
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 70
  liveness:
    path: /is_alive
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  readiness:
    path: /is_ready
    initialDelay: 60
    periodSeconds: 5
    timeout: 5
    failureThreshold: 3
  leaderElection: true
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 384Mi
  vault:
    enabled: true
    paths:
      - kvPath: serviceuser/data/prod/isdialogmelding
        mountPath: /secrets/serviceuser
  webproxy: true
  ingresses:
    - "https://isdialogmelding.intern.nav.no"
  env:
    - name: KTOR_ENV
      value: "production"
    - name: MQGATEWAY_HOSTNAME
      value: "a01apvl269.adeo.no"
    - name: MQGATEWAY_PORT
      value: '1414'
    - name: MQGATEWAY_NAME
      value: "MPLS02"
    - name: MQGATEWAY_CHANNEL_NAME
      value: "P_isdialogmelding"
    - name: MOTTAK_QUEUE_UTSENDING_QUEUENAME
      value: QA.P414.IU03_UTSENDING

